# Custom Language File for Launcher Customizer

[ejs.app]
title = "DTP Studio Launcher"

[ejs.landing]
mediaGitHubURL = "https://sites.google.com/view/dtpstudios/inicio?authuser=1"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@DeathtothepantherStudio"
mediaDiscordURL = "https://discord.gg/BMNbYSZeHY"

[ejs.settings]
sourceGithubLink = ""
supportLink = ""

[ejs.welcome]
welcomeHeader = "Bienvenido al launcher oficial de DTP Studio para Minecraft."
welcomeDescription = "Este launcher ha sido creado para ofrecerte un acceso rápido y sencillo a nuestros servidores exclusivos y eventos dentro del universo de Minecraft. Con él, podrás disfrutar de una experiencia de juego optimizada, diseñada para mejorar tu interacción con nuestros proyectos y facilitar tu participación en nuestra comunidad."
welcomeDescCTA = "Explora nuevos mundos, sumérgete en servidores de roleplay y mantente al tanto de las novedades de DTP Studio."
